# Use the official Node.js image as the base image
FROM node:23.5.0

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY portfolio/frontend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY portfolio/frontend/ .

# Expose the port the app runs on
EXPOSE 1234

# Command to run the application
CMD ["npm", "run", "dev-js"]